Add `NUMBER_OF_INPUTS` to `poseidon-proof`
privacy-scaling-explorations/zk-kit pull request #124
Opened 2024-01-12 11:18 UTC by 0xjei

## Related Issue
See #116

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other Information
This PR introduces the use of `digest` to compute the `nullifier` output signal instead of the `preimage` as specified in the #116

2024-01-12 14:05 UTC, cedoor requested changes
Great job, just a few corrections in the comments!

2024-01-12 14:05 UTC, cedoor commented on packages/circuits/circom/poseidon-proof.circom
>  // This circuit can be used to prove the possession of a pre-image of a
```suggestion
// This circuit can be used to prove the possession of pre-images of a
```

2024-01-12 14:05 UTC, cedoor commented on packages/circuits/circom/poseidon-proof.circom
> +    // A nullifier is also computed using both the pre-image and the digest, providing a value
```suggestion    
    // A nullifier is also computed using both the scope and the digest, providing a value
```

2024-01-12 18:04 UTC, 0xjei commented
Converted to draft to make changes to `@zk-kit/poseidon-proof` before merging this feature.

2024-01-16 13:45 UTC, 0xjei commented
Ready for review @cedoor

2024-01-16 15:01 UTC, cedoor requested changes
Great job @0xjei! Just a small fix for a bug that was already there before your PR.

2024-01-16 16:07 UTC, cedoor approved these changes

2024-01-16 16:20 UTC, merged